# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SuperNEMO
description: > # this means to ignore newlines until "baseurl:"
  SuperNEMO Double Beta Decay Search Experiment. This
  will appear in the document head meta for Google
  search results and the fedd.xml site description.
# google_analytics:
baseurl: "" # the subpath of this site e.g. /blog
url: "" # the base hostname and protocol for this site, e.g. http://example.com

# Contacts
#email: your-email@domain.com
github_username: SuperNEMO-DBD
#twitter_username:

# Collections:
collections:
  publications:
  nemothreepubs:
  carousel_images:
    # When pub format is better defined, can output one per page ala ADS
    #output: true

# Build settings
gems:
  - jekyll-feed
  - jekyll-mentions
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - snjekyll
  - README.md
