#!/usr/bin/env bash
set -ev # halt script on error, print lines

bundle exec jekyll build
# Debug output to ensure full reporting, ignore "Falaise" relative
# url for now as this is constructed by GitHub pages on hosting.
bundle exec htmlproofer --log-level debug --url-ignore "Falaise" ./_site

